### ISSUE TITLE
Clean up copy / deepcopy usage and implementation

### ISSUE THREAD

**Issue by gfrances** [aig-upf/tarski#23] opened 2018-09-14 10:51 UTC
We have a few overrides of the special methods __copy__ and __deepcopy__ in the FOL syntax classes in Tarski. Most of them are not necessary, as they do exactly what the `copy.copy` and `copy.deepcopy` methods should do. One of them is key however, and does a different thing. The one in the Sort class:

```
    def __deepcopy__(self, memo):
        memo[id(self)] = self
        return self
```

Which prevents an otherwise undesirable circular recursion, which is the one that leads from a Sort to itself, because Sort objects have a language attribute, and language objects contain the sorts in many places. `copy.deepcopy` should deal with this correctly, but it doesn't. I've traced down the cause of this "error", and it is due to the Sort object being only partially built because it is being deepcopied, but the deepcopy process requiring the value of some of its attributes to be set, e.g. to compute its hash value, etc.

Without going too much into detail on why that happens, I think it'd be better to decide how we want to `deepcopy` these objects, because the (circular) dependencies are many, and the Language objects are quite heavy. For that, it'd be good to collect what are the use cases.
@miquelramirez , you mentioned that this is necessary for transformations, etc.
Could you elaborate a bit on that?

In case the above is not too clear (sorry, in a bit of a rush now), another way of looking at this is: if I want to deepcopy, say, a Constant object with value Constant(1)... do I want this deepcopy to trigger the whole copy of the entire first-order language, including duplicating all sorts, all other constants, functions, predicates, and so on? Probably not, although I'm not 100% sure. If we have a clear idea of what we want this for, we'll be able to "short-circuit" the deep-copying mechanism in the appropriate places (as in the method above, that stops the recursion and does a simple shallow copy), and document that adequately.

**Comment by gfrances** [comment] 2018-09-14 11:51
Not sure which attribute `L` you mean?

One relevant point is that we don't want to implement something that breaks with the standard semantics of copy / deepcopy. E.g. if a user of the library deepcopies a language, she would expect to get a truly deep-copy, etc.

Another alternative of course is to implement ourselves a different copy module that works with our classes only, and document appropriately. To discuss which is the best alternative, though, I'd say it'd be good to have some concrete use cases at hand.

**Comment by miquelramirez** [comment] 2018-09-14 12:10
> Not sure which attribute L you mean?

```L``` = language. That was the old name the property pointing to the language associated with a term had.

> One relevant point is that we don't want to implement something that breaks with the standard semantics of copy / deepcopy. E.g. if a user of the library deepcopies a language, she would expect to get a truly deep-copy, etc.

The standard semantics of copy/deepcopy are as useful as those of C++. We overwrite very often constructors in C++ for the very same reasons as here (efficiency, correctness, etc.). So much for "breaking with the standard". I would rather say, "overwriting default behaviour".

I don't find productive to obsess with purity on a subject which is obviously a major Python kludge. Anybody trying to write a white box framework as we are has to work around this stuff Bugs in Python libraries regarding copying and circularity etc. aren't precisely rare. I don't think it is a matter of messy programming or friction on the design of those libraries, but actually the hallmark of something that is broken outside of the specific use cases of the original niche of Python as a scripting language.

> Another alternative of course is to implement ourselves a different copy module that works with our classes only, and document appropriately. 

That is overkill. 

> To discuss which is the best alternative, though, I'd say it'd be good to have some concrete use cases at hand.

Well, the concrete use cases are quite clear in my opinion, the codes requiring copying are quite easy to find.

Formulas are needed to be copied in their integrity to implement transformations like Quantifier Elimination and for grounding. In general, whatever transformation requiring to preserve structure and change only a part of the expression (either a leaf, as is the case in the two example above, or whole subformulas as is the case with rewriting formulas to CNF). In both of those, the original formula with the variables is a template that is then copied. Another further complication with formulas is that we need to copy the whole expression tree, recursively, and you can find literally anything.

In other cases, copies are needed to avoid doing changes "in place" to the formula which would make standard algorithms for the transformations unsound or complicate their implementation them arbitrarily for no clear gain.

The reason for having several has been already explained. I am not sure what is the purpose of a comment like "they do exactly what default copy/deepcopy methods do" when the code conspicuously points otherwise.

On the Term hierarchy explicit copy/deepcopy overrides have been deprecated for a very long time. You just pointed out that with the current implementation, where if somebody is copying a formula with a constant will be copying the language as well. That I think is a bug, definitely not intended behaviour. A pretty direct way of solving this issue is to overwrite the __deepcopy__ method of Constant and avoid calling deepcopy on the ```sort``` attribute.

That needs to be taken care of. In general, we will want to overwrite the __deepcopy__ operator for those objects to avoid circularities or inefficiencies like that. 

Regarding ```Sort``` I can't think of a use case where anybody would want to copy them. But since this is a framework meant to be used in ways we haven't think of, the safe thing would be to construct things defensively... so the current implementation is basically being defensive, trying to avoid copying itself.

Last, I would like to know what is the issue/test case which has triggered this discussion. Is a test case on ```master```?

**Comment by gfrances** [comment] 2018-09-14 14:27
No need to get angry! :-)

> The reason for having several overloads has been already explained. I am not sure what is the purpose of a comment like "they do exactly what default copy/deepcopy methods do" when the code conspicuously points otherwise.

I honestly still don't understand their purpose. That's why I thought it could be good to add some code comments documenting the intention. You say it's conspicuously obvious, but look at these two overrides:

```
    def __copy__(self):
        newone = type(self)()
        newone.__dict__.update(self.__dict__)
        return newone

    def __deepcopy__(self, memo):
        newone = type(self)()
        memo[id(self)] = newone
        for k, v in self.__dict__.items():
            setattr(newone, k, copy.deepcopy(v, memo))
        return newone
```
I still don't understand what makes them necessary: my point is that if that I take them out, everything will work exactly the same, as they are implementing exactly the default behavior. I think you mentioned elsewhere that 
> The bit you're missing is that default copy "methods" only works with classes with no arguments in their constructor.

I don't think that't the case at all, have never before run into that issue, and that appears nowhere in the documentation of copy/deepcopy. Now, the overrides that _do_ make a difference, are the ones in classes `Sort`, `Predicate`, and `Function`, that do something which is not the default behaviour of deepcopy:

```
    def __deepcopy__(self, memo):
        memo[id(self)] = self
        return self
```

I have uploaded some changes to see this in a new branch (bf2978541728535e6f9a3e157693b507099edbb9).
There's also a `test_copying_and_equality` test method (also in master). If you can add there some code which makes some test fail where with the code before (i.e. in master) didn't fail, I'll be happy to study it and try to understand what's going on - and perhaps document that so that next time I don't have to scratch my head around this!

**Comment by gfrances** [comment] 2018-09-14 14:34
> On the Term hierarchy explicit copy/deepcopy overrides have been deprecated for a very long time. You just pointed out that with the current implementation, where if somebody is copying a formula with a constant will be copying the language as well. That I think is a bug, definitely not intended behaviour. A pretty direct way of solving this issue is to overwrite the **deepcopy** method of Constant and avoid calling deepcopy on the `sort` attribute.
> 
> That needs to be taken care of. In general, we will want to overwrite the **deepcopy** operator for those objects to avoid circularities or inefficiencies like that.

That sounds quite reasonable to me. A similar (maybe simpler?) fix would  be to shortcircuit the deepcopy operator of Language so that it performs a shallow copy (documenting that, of course); and provide, if necessary, and only for language, a method `clone`, or `deepcopy`, or whatever name, that _does_ actually a deep copy. With that single change, I think (but not 100% sure) that all of this would be solved, and deepcopies would be much cheaper. The "new" semantics of deepcopy for FOL objects would be something akin to "performs a deep copy of the object _within the same FOL language_". 
But have to check this more carefully.

**Comment by miquelramirez** [comment] 2018-09-14 23:01
Okay, I just merged ```contingent``` into ```dev-0.2.0``` and it indeed looks like we're not breaking the default implementations of ```copy``` and ```deepcopy``` as we used to.

**Comment by miquelramirez** [comment] 2018-09-14 23:04
> That sounds quite reasonable to me. A similar (maybe simpler?) fix would be to shortcircuit the deepcopy operator of Language so that it performs a shallow copy (documenting that, of course); and provide, if necessary, and only for language, a method clone, or deepcopy, or whatever name, that does actually a deep copy. 

This should be handled by the objects referring to ```Language```, as then we can use the default behaviour of deepcopy for Language.

> The "new" semantics of deepcopy for FOL objects would be something akin to "performs a deep copy of the object within the same FOL language".

That makes sense

**Comment by miquelramirez** [comment] 2018-09-14 23:08
> There's also a test_copying_and_equality test method (also in master). If you can add there some code which makes some test fail where with the code before (i.e. in master) didn't fail, I'll be happy to study it and try to understand what's going on - and perhaps document that so that next time I don't have to scratch my head around this!

Please, don't do direct commits like that to ```master```, because they're hard to track for me and test the integration with the stuff in ```dev-0.2.0```. Committing directly to ```dev-0.2.0``` is recommended.

**Comment by miquelramirez** [comment] 2018-09-17 01:43
I am closing this one down, as ```dev-0.2.0``` has now incorporated all the changes discussed here.

**Closed by miquelramirez** 2018-09-17 01:43 UTC
