### ISSUE TITLE
Error: while parsing ipc-2011/tidybot, ipc-2014/seq-sat/Floortile and ipc-2011/parcprinter

### ISSUE THREAD

**Issue by anubhav-cs** [aig-upf/tarski#79] opened 2019-10-17 12:25 UTC
Encounter few issues while parsing  <ipc-2011/tidybot> and <ipc-2014/seq-sat/Floortile> domains, and grounding<ipc-2011/parcprinter> domain (Devel branch)

_Reproduction_:- The issues can be reproduced by cloning [test-tests](https://github.com/anubhav-cs/tarski-tests/blob/master/old_test-suite) and running test.py (different domain and problem files can be loaded from line 163-178 in the code).

-  [Error Log 1](https://github.com/anubhav-cs/tarski-tests/blob/master/old_test-suite/error_floortile.log)  - floortile
-  [Error Log 2](https://github.com/anubhav-cs/tarski-tests/blob/master/old_test-suite/error_tidybot.log)  - tidybot
-  [Error Log 3](https://github.com/anubhav-cs/tarski-tests/blob/master/old_test-suite/error_parcprinter.log)  - parcprinter

**Comment by miquelramirez** [comment] 2019-10-17 22:42
Regarding Error #2 you could in principle have a construct like `(cart cart)` in PDDL, as each of the `cart` tokens would be assigned a unique semantic role (the first a predicate, the second an object). The issue is that then you would not have a well defined first-order language, IIRC it is not allowed to have the same symbol map to objects belonging to different sorts, or worse, symbols mapping both onto objects and predicates.

A possible solution - imo - would be that `tarski` complains by default as it is doing now, and this behaviour can be changed by the user to rename these symbols (by prepending an underscore for instance). The problem with this is that it would break third plan validators (such as `VAL`).

**Comment by anubhav-cs** [comment] 2019-10-21 23:06
I did some runs on domains in various [benchmarks](https://github.com/anubhav-cs/tarski-tests/tree/master/benchmarks), and I am including a  [csv file](https://github.com/anubhav-cs/tarski-tests/blob/master/benchmarks/tarski_grounding_status.csv) with status of success/error. Also, there is a [zip](https://github.com/anubhav-cs/tarski-tests/blob/master/benchmarks/tarski_grounding_error_logs.zip) with the error logs.
 - CSV - https://github.com/anubhav-cs/tarski-tests/blob/master/benchmarks/tarski_grounding_status.csv
 - Logs - https://github.com/anubhav-cs/tarski-tests/blob/master/benchmarks/tarski_grounding_error_logs.zip

_Note_ - While the tarski's grounding performance is impressive, it takes a little bit longer to load and parse the pddl file itself(in comparison to FD). This is much worse for a specifc domain `ecai12/cybersec`, where it took  almost 10 minutes to load the pddl(FD took 18 seconds). I have the attached profiler log files which can be viewed with `kcachegrind`.

**Comment by gfrances** [comment] 2019-10-28 18:13
Hi @anubhav-cs. This is all very useful, thanks for the reporting.
I have fixed the bug in parcprinter, which was due to poor handling of actions starting with capital letter (Clingo assumes that anything starting with a capital letter is a variable). I have also fixed the problem with `total-cost` atoms, which are now properly ignored.

I'll try to test tomorrow with some more of the domains you report are faulty.

As for the performance, I'll have a look at that as well; one possible reason could be that it seems the logic programs we generate are not exactly the same as the ones generated by the Fast Downward preprocessor, particularly wrt negated preconditions, and possibly other features as well. We haven't had the time to further investigate this, although @abcorrea might be able to shed some more light on this topic. Of course it could well be that this has nothing to do with what you observe in cybersec, I'll see if I can find some time to investigate.

**Comment by gfrances** [comment] 2019-10-29 14:07
I have added some extra tests for some of the buggy domains you mentioned, @anubhav-cs. Since many of the problems arise because of incomplete `requirement` sections in the PDDL domain, I have implemented a simple "lenient" parsing mode that can be configured on demand and assumes that this requirements are specified even if they are not. You can check the details of how to use this [here in the relevant commit](https://github.com/aig-upf/tarski/commit/58b2d1a861246091f476abf745a86313a63cfe47#diff-2655586f7b0de835bbe487ed9c1b1dc2R26).

All the bugs I explored so far where related to the same bugs I corrected yesterday. Some domains though are not compliant with the PDDL 3.1 in other manners; these still cannot be parsed. A quick list of the ones I've identified and the reason why they are not compliant [is here](https://github.com/aig-upf/tarski/commit/fbbd27dfb9243cb943717a9f1716cd170d71fd73#diff-096182624648eef430c4326a9bede0e2R28). It most cases is straight-forward to fix the domain encoding, so I'd suggest doing this if you're interested in trying the parser with them; from my point of view it doesn't make much sense to refactor the parser to accept buggy domains.

Other than that, do you have an automated script to produce a CSV like the one you sent last week, but updated to the latest code changes? Could be interesting to check what's still missing.

**Comment by anubhav-cs** [comment] 2019-10-30 13:58
Thank you very much @gfrances, I will run the grounder on the domains again and let you know.

Also, I noticed that the grounder generates temp files in `/tmp` folder on Ubuntu. These are not deleted after each run and can pile up to few gigabytes if left unchecked.

**Comment by anubhav-cs** [comment] 2019-11-28 19:14
Hello @gfrances @miquelramirez,

I have uploaded a [tarski test-suite](https://github.com/anubhav-cs/tarski-tests), which can be used to test grounding for 1 problem from each of the 146 domains in [classical domains](https://bitbucket.org/planning-researchers/classical-domains/src/master/). There are some `failure_report.csv` and `status_report.csv` along with the `stderr.log` files in the repo, which can be automatically regenerated by executing `test.sh`.

Also, I observed that because of some recent code changes in _Devel_ branch Tarski is unable to ground couple of domains from *IPC-2018 - Spider and Organic Synthesis*. The last known commit, which was working fine for those domains, is [commit 87f94237cd1dda35f9c551c66d81bfbe72e06f8e](https://github.com/aig-upf/tarski/commit/87f94237cd1dda35f9c551c66d81bfbe72e06f8e). Apart from that, *cybersec* is the only domain which significantly stands out in terms of very high run-time and memory consumption by gringo.

**Comment by miquelramirez** [comment] 2019-11-29 01:21
Thank you very much @anubhav-cs for tracking down these issues and doing the work of cataloguing them.

**Comment by anubhav-cs** [comment] 2019-11-30 05:21
Hi @miquelramirez @gfrances,

A particular [problem.pddl](https://github.com/anubhav-cs/tarski-tests/blob/master/classical/tetris-sat14-strips/p026.pddl) in Tetris [domain](https://github.com/anubhav-cs/tarski-tests/blob/master/classical/tetris-sat14-strips/domain.pddl), from IPC-2014, is resulting in duplicate definition [error](https://github.com/anubhav-cs/tarski-tests/blob/master/tetris-sat14-strips_stderr.log). I am unable to pin-point what's wrong in the PDDL, hence requesting you to take a look.

Note - I have added this problem to the [test-suite](https://github.com/anubhav-cs/tarski-tests)

**Comment by anubhav-cs** [comment] 2019-11-30 11:08
@miquelramirez @gfrances 
Upon more extensive testing across all problems in IPC-2018, I have noted the following additional issues.

1. [Flashfill domain](https://github.com/anubhav-cs/tarski-tests/blob/master/classical/flashfill-sat18/domain-p15.pddl)  - [p15](https://github.com/anubhav-cs/tarski-tests/blob/master/classical/flashfill-sat18/p15.pddl) - gringo runs out of memory - [error](https://github.com/anubhav-cs/tarski-tests/blob/master/flashfill-sat18-strips_stderr.log)
2. [Organic-synthesis domain](https://github.com/anubhav-cs/tarski-tests/blob/master/classical/organic-synthesis-sat18/domain-p18.pddl) - p04, p09, p10, p11, [p18](https://github.com/anubhav-cs/tarski-tests/blob/master/classical/organic-synthesis-sat18/p18.pddl), p19 and  p20 - gringo runs out of memory - [error](https://github.com/anubhav-cs/tarski-tests/blob/master/organic-synthesis-sat18-strips_stderr.log)
3. Observed that some `tmpxxxx` files in `/tmp` directory are more than 500 MB. The total size exceeded the server hard-disk space. As a workaround, I delete any file in  `/tmp` that is older than 5 minutes. but it still consumes up to 20 GB hard-disk space.

Note - I have added the highlighted problems to the [test-suite](https://github.com/anubhav-cs/tarski-tests)

**Comment by gfrances** [comment] 2019-12-04 22:46
Hi @anubhav-cs ,

thanks for the extensive reporting. I've fixed some bugs in the ASP component, although not sure if they are the ones you report. I'll be checking this as I find time. BTW, I wonder if it could be a good idea to integrate the test scripts you've developed into the main pytest scripts for tarski?

As for the issue with the temporary files in /tmp, since commit 89ed35d380 now we remove explicitly those temporary files, so this part at least should be fixed.

**Comment by anubhav-cs** [comment] 2019-12-05 09:06
Hi @gfrances ,

Thanks for fixing the `tmp*` files issue!

Also, I agree that it is a good idea to integrate the test scripts into Tarski. Unfortunately, I didn't create the scripts with `pytest` in mind. Currently, a shell script `test.sh` invokes the `taski_test.py` python script for each domain, generates status report and redirects stderr to log files. I will make a single python file later this week _pytest compatible_ and create a pull request. 

_Note -_  I have added the a `-l or --lenient` mode to the test scripts, and also reverted the domain and problem PDDL file in `test-suite` to the original (not-modified). This will give a clear idea on the grounding status for each domain. Also, there seems to be some bug in `lenient or strict_with_pddl_requirements=False` mode, as the number of domains which failed to ground increased to _84_.

**Comment by gfrances** [comment] 2019-12-05 10:43
About this `strict_with_requirements` option, I fixed some bug yesterday night, so maybe that accounts for your observation?

**Comment by anubhav-cs** [comment] 2019-12-05 15:37
The tests were done on the latest commit, but I saw the errors last week as well. I am seeing a new error as below, in multiple domains, when `strict_with_requirements=False`. There is no such error when  `strict_with_requirements=True`.
    
       tarski.errors.DuplicateFunctionDefinition: Duplicate definition of element "ite": "ite"

**Comment by gfrances** [comment] 2019-12-05 15:44
Oh I see, this is the bug I thought I had fixed, but apparently I didn't push the changes, since I don't see them in the commit log - sorry for that, I'll push that on the weekend, as I am away until then. I'll also have a deeper look at the test results then.

**Comment by gfrances** [comment] 2019-12-30 12:16
Hi @anubhav-cs , @miquelramirez . Commit 32876c9 (in `devel` only) changes a bit the formulation of the reachability LP to align it with the one described by Malte in his paper. The change is that now we ignore atoms of the form X!=Y in preconditions and goal, whereas before we were mapping them to LP atoms X != Y (with which BTW we could no longer guarantee polynomiality of the preprocessing!). Perhaps you'd be interested in rerunning the experiment script, @anubhav-cs , this might certainly make a difference in domains such as organic synthesis. I am running some benchmarks on my side as well, but will take a while to finish.

**Comment by gfrances** [comment] 2019-12-30 12:18
(btw if you test this, take the latest commit on `devel`, there was a weird bug that was arising when using old versions of Gringo that is now fixed)

**Comment by miquelramirez** [comment] 2021-07-10 07:38
I think we got past this issue already

**Closed by miquelramirez** 2021-07-10 07:38 UTC
